spring:
  application:
    name: ${SPRING_APPLICATION_NAME:inventario}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}

server:
  port: ${SERVER_PORT:8080}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION:172800000}

app:
  root:
    name: ${ROOT_USER_NAME:Super Admin}
    username: ${ROOT_USER_USERNAME:root}
    password: ${ROOT_USER_PASSWORD:}0000}